### ISSUE TITLE
Version for Apple Silicon?

### ISSUE THREAD

**Issue by bobjacobsen** [jinput/jinput#140]
I'm looking for a version of JInput that will work with native Apple Silicon. JInput 2.0.9 doesn't seem to work, with the error:
```
     [java] java.lang.ClassNotFoundException: projects/JMRI/net.bobis.jinput.hidraw.HidRawEnvironmentPlugin
     [java] 	at java.base/java.lang.Class.forName0(Native Method)
     [java] 	at java.base/java.lang.Class.forName(Class.java:315)
     [java] 	at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:133)

```

Has anybody built a custom version that will do this? 

Or do I really need to find some new version of a subcomponent? In that case, which?

**Comment by Endolf** [comment]
If the APIs in the newer OSX are the same, it should just need compiling on the right platform, I don't have access to any apple stuff though so can't really help with that.
The package names in that class not found exception are not right either, looks like a 3rd party plugin has been specified in the properties.

**Comment by bobjacobsen** [comment]
Thanks!

To get a fat binary containing both x86_64 and arm64 architectures, I had to add "-arch arm64" alongside the existing "-arch x86_64" in the x86_64_flags definition in the plugins/OSX/build.xml file.  

I also had to make some small adjustments to bring the paths up to date with how macOS 10.10 and later is organized.  Unfortunately, that makes the build.xml file no longer compatible with building on macOS 10.5 through 10.9.  

Do you want me to make a PR out of these changes?

I've attached the resulting libjinput-osx.jnilib file in .zip form.

[libjinput-osx.jnilib.zip](https://github.com/jinput/jinput/files/13805133/libjinput-osx.jnilib.zip)

**Comment by bobjacobsen** [comment]
(I attached the wrong file version, so have edited the original comment to attach the right one.  My apologies for the mistake)

**Comment by Endolf** [comment]
It might be possible in the build file to detect the OSX version and set the paths appropriately?

**Comment by bobjacobsen** [comment]
I've got it working back to macOS 10.5, which is the furthest back that the SDK will go if you also want support for Apple Silicon.  Should I put this in a PR?

**Comment by Endolf** [comment]
That'd be great!, thanks.

**Comment by bobjacobsen** [comment]
See #155 for related PR.  Thanks!

**Comment by Endolf** [comment]
I don't have access to any apple silicon, could you test the natives from the github actions [here](https://github.com/jinput/jinput/actions/runs/7660984627) please?

**Comment by bobjacobsen** [comment]
Seems to work fine.  I've got only limited USB devices to check, but they are all functioning well.

**Comment by Endolf** [comment]
Great, just need to work out how to do a maven release using artifacts built in github....

**Comment by Endolf** [comment]
Now got github action that deploys to maven central for snapshot builds, just need to work on the release process so we can get 2.0.10 out to close this.
