### ISSUE TITLE
Is Windows 10 supported?

### ISSUE THREAD

**Issue by manudahmen** [jinput/jinput#15]
_

> C:\Users\manuel\Projets\3D\Power-and-Damages>"C:\Program Files\Java\jdk1.8.0_74\bin\java"  -classpath ".;target\production\Power-and-Damages1\pad.jar;lib\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\CopyLibs\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\Empty3-35\*;[...] -Djava.library.path=".;lib; [...]" info.emptycanvas.apps.darz.input.Joystick 
> WARNING: Found unknown Windows version: Windows 10
> Attempting to use default windows plug-in.
> Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin

_

```

java.lang.UnsatisfiedLinkError: no jinput-dx8_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at net.java.games.input.DirectInputEnvironmentPlugin$1.run(DirectInputEnvironmentPlugin.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.java.games.input.DirectInputEnvironmentPlugin.loadLibrary(DirectInputEnvironmentPlugin.java:67)
	at net.java.games.input.DirectInputEnvironmentPlugin.<clinit>(DirectInputEnvironmentPlugin.java:109)
	at net.java.games.input.DirectAndRawInputEnvironmentPlugin.<init>(DirectAndRawInputEnvironmentPlugin.java:45)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:157)
	at info.emptycanvas.apps.darz.input.Joystick.main(Joystick.java:12)
net.java.games.input.DirectAndRawInputEnvironmentPlugin is not supported
java.lang.UnsatisfiedLinkError: no jinput-raw_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at net.java.games.input.RawInputEnvironmentPlugin$1.run(RawInputEnvironmentPlugin.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.java.games.input.RawInputEnvironmentPlugin.loadLibrary(RawInputEnvironmentPlugin.java:67)
	at net.java.games.input.RawInputEnvironmentPlugin.<clinit>(RawInputEnvironmentPlugin.java:109)
	at net.java.games.input.DirectAndRawInputEnvironmentPlugin.<init>(DirectAndRawInputEnvironmentPlugin.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:157)
	at info.emptycanvas.apps.darz.input.Joystick.main(Joystick.java:12)

Process finished with exit code 0

```

**Comment by Endolf** [comment]
Is there a jinput-dx8_64.dll in your lib directory?

**Comment by manudahmen** [comment]
yes.

**Comment by Endolf** [comment]
Windows 10 is supported and the logs suggest it has tried to load the plugin.

**Comment by manudahmen** [comment]
C:\Users\manuel\Projets\3D\Power-and-Damages>"C:\Program Files\Java\jdk1.8.0_74\bin\java"  -classpath ".;target\production\Power-and-Damages1\pad.jar;lib\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\CopyLibs\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\Empty3-35\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\EmptyCanvas\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\idea_libs\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\apk\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\apk\unsigned\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\etc\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\jar\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\jar\atomic\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\jnlp-files\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\jnlp-files\atomic\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\android-aarch64\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\android-armv6\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\linux-amd64\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\linux-armv6\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\linux-armv6hf\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\linux-i586\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\macosx-universal\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\solaris-amd64\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\solaris-i586\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\windows-amd64\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib\windows-i586\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\doc\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\doc\3rdparty\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\jar\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native\freebsd\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native\linux\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native\macosx\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native\openbsd\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native\solaris\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native\windows\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\res\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\res\logo\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\res\spaceinvaders\*;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\swing-layout\*" -Djava.library.path=".;lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\apk;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\jar;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\jnlp-files;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\jogamp-all-platforms\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\doc;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\native;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\res;C:\Users\manuel\Projets\3D\Power-and-Damages\lib\lwjgl-2.9.4\res;C:\Users\manuel\Projets\3D\Power-and-Damages\lib" info.emptycanvas.apps.darz.input.Joystick
