### ISSUE TITLE
"no jinput-dx8_64 in java.library.path" desipte the file being in the path

### ISSUE THREAD

**Issue by MightyElemental** [jinput/jinput#42]
I get these errors when I launch my program.

> java.lang.UnsatisfiedLinkError: no jinput-dx8_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at net.java.games.input.DirectInputEnvironmentPlugin.lambda$loadLibrary$0(DirectInputEnvironmentPlugin.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.java.games.input.DirectInputEnvironmentPlugin.loadLibrary(DirectInputEnvironmentPlugin.java:67)
	at net.java.games.input.DirectInputEnvironmentPlugin.<clinit>(DirectInputEnvironmentPlugin.java:98)
	at net.java.games.input.DirectAndRawInputEnvironmentPlugin.<init>(DirectAndRawInputEnvironmentPlugin.java:45)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:134)
	at org.lwjgl.input.Controllers.create(Controllers.java:71)

> java.lang.UnsatisfiedLinkError: no jinput-raw_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at net.java.games.input.RawInputEnvironmentPlugin.lambda$loadLibrary$0(RawInputEnvironmentPlugin.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.java.games.input.RawInputEnvironmentPlugin.loadLibrary(RawInputEnvironmentPlugin.java:67)
	at net.java.games.input.RawInputEnvironmentPlugin.<clinit>(RawInputEnvironmentPlugin.java:98)
	at net.java.games.input.DirectAndRawInputEnvironmentPlugin.<init>(DirectAndRawInputEnvironmentPlugin.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:134)
	at org.lwjgl.input.Controllers.create(Controllers.java:71)

Thing is, the library path contains all the native files that it asks for. 'jinput-dx8_64.dll' and 'jinput-raw_64.dll'.
LWGJL does not throw any errors and its natives are in the same path.
I'm using the latest version of windows 10 along with jinput 2.0.9.

**Comment by RalleYTN** [comment]
Try this:
```java
System.setProperty("net.java.games.input.librarypath", new File("Path/To/The/Folder/With/Natives").getAbsolutePath());
```

**Comment by MightyElemental** [comment]
@RalleYTN That is what I am using currently. I think the issue is that I am not using the natives from the jar that it came with. (I only thought about this a few days ago)
Do you know how to add the jar to the native path using maven?

**Comment by RalleYTN** [comment]
@MightyElemental
Sadly no.

I am always extracting the natives from the JARS using WinRar, put them in a folder and map the absolute path to this folder in the property "net.java.games.input.librarypath" in a static block of my main class.

it works.

**Comment by MightyElemental** [comment]
@RalleYTN Thanks. This worked. Not sure why it does not just use the default library path but thanks.

**Comment by i-make-robots** [comment]
You downloaded the project and built it from source.  Are these files in your root path?

![L](https://user-images.githubusercontent.com/1464454/90042902-2ac99500-dc80-11ea-89bd-83532781ffa1.PNG)

**Comment by Hubcapp** [comment]
Thanks, worked. Still an "issue" as of December 2021.
