### ISSUE TITLE
Windows 10 Update + jinput + Xbox Controller Issue

### ISSUE THREAD

**Issue by SirWilli** [jinput/jinput#8]
hey,

with the last windows 10 update I encountered an issue with jinput which freezes the application.
This issue only happens if I have my Xbox One Controller plugged in.

Thread dump:
```
"Client thread" - Thread t@1
   java.lang.Thread.State: RUNNABLE
    at net.java.games.input.IDirectInputDevice.nAcquire(Native Method)
    at net.java.games.input.IDirectInputDevice.acquire(IDirectInputDevice.java:365)
    at net.java.games.input.IDirectInputDevice.setBufferSize(IDirectInputDevice.java:514)
    - locked <5ca1251c> (a net.java.games.input.IDirectInputDevice)
    at net.java.games.input.IDirectInputDevice.<init>(IDirectInputDevice.java:265)
    at net.java.games.input.IDirectInput.addDevice(IDirectInput.java:82)
    at net.java.games.input.IDirectInput.nEnumDevices(Native Method)
    at net.java.games.input.IDirectInput.enumDevices(IDirectInput.java:73)
    at net.java.games.input.IDirectInput.<init>(IDirectInput.java:59)
    at net.java.games.input.DirectInputEnvironmentPlugin.enumControllers(DirectInputEnvironmentPlugin.java:218)
    at net.java.games.input.DirectInputEnvironmentPlugin.<init>(DirectInputEnvironmentPlugin.java:126)
    at net.java.games.input.DirectAndRawInputEnvironmentPlugin.<init>(DirectAndRawInputEnvironmentPlugin.java:45)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at 
```

**Comment by monsieurmax** [comment]
Got the same issue on my game.

I had to make secure the controllers detection in a thread with a timeout feature.

**Comment by Ali-RS** [comment]
For those who have the same problem, this solution might help

https://stackoverflow.com/a/68828083/15218487
